### ISSUE TITLE
DBT docs are not evaluating variables in the documentation output.

### ISSUE THREAD

**Issue by sokser** [fishtown-analytics/dbt-docs#82]
DBT docs are not evaluating variables in the documentation output. For example, I have
```
- name:  var('company_name')
  description: "The company name after being passed through a cleansing process."
  tests:
    - not_null
```
And while it displays and runs tests on the column, it displays the column name in docs as
`var('company_name')`
I would rather want it to point to the underlying value defined in the dbt_project.yml and the value is `cleaned_name` that should show in the doc.
