### ISSUE TITLE
Tags break sources in the lineage view

### ISSUE THREAD

**Issue by drewbanin** [fishtown-analytics/dbt-docs#93]
From Slack

Given an example source configured with a tag:

```
version: 2
sources:
  - name: myproject
    tags:
      - mytag
    tables:
      - name: mytable
```

The source is not rendered in the lineage DAG. Removing the `mytag` tag fixes the issue.
